server {
    listen 80;
    listen [::]:80;
    
    server_name {{PUBLIC_URL}};
    
    location / {
        root /usr/share/jitsi-meet;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    
    location /http-bind {
        proxy_pass http://localhost:5280;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
    }
    
    location /xmpp-websocket {
        proxy_pass http://localhost:5280;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
    
    location ~ ^/(images|css|static|libs|fonts|lang)/ {
        root /usr/share/jitsi-meet;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
